# Generated by Django 3.1.7 on 2021-03-04 04:06

from django.db import migrations

import datetime
import random

def randomDateTime():
    return datetime.datetime(random.randint(2010,2030), random.randint(1,12), random.randint(1,20), random.randint(0, 23))

def populate_db(apps, schema_editor):
    blogs = [
        {
            "title": "A random post",
            "author": "A random poster",
            "content": """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent orci diam, ultrices ornare volutpat at, rutrum ut urna. In accumsan sit amet mauris ut vehicula. Pellentesque gravida rutrum mattis. In suscipit vulputate magna, eu iaculis orci lobortis ac. Duis non ligula id risus porttitor sodales vel sit amet neque. Donec quis convallis ipsum, eget egestas mauris. Quisque ante urna, venenatis vel neque in, interdum malesuada nisl. Aliquam in augue consequat, gravida dolor ut, consectetur ipsum. Nulla vitae lorem urna. Nunc suscipit lacus sem, vitae iaculis mauris sollicitudin aliquet. Vestibulum libero nisl, pellentesque eu felis porta, varius pulvinar sapien. Phasellus pulvinar nulla justo, eu mollis erat ornare ac.

Duis id aliquam erat. Cras sit amet leo mattis, auctor sem non, pulvinar massa. Donec ac volutpat ante. Sed vitae leo venenatis, hendrerit arcu in, sodales diam. Vivamus id ornare enim. Aenean eleifend risus ut metus volutpat gravida sed quis ante. Duis sagittis elit at orci cursus commodo. Pellentesque lacinia velit enim, a dignissim tortor tincidunt vel. Suspendisse a egestas eros. Vivamus semper hendrerit tellus. Morbi convallis ex id viverra suscipit. Aliquam interdum, eros ut egestas eleifend, metus diam ultrices ex, in dignissim justo justo ut diam. Suspendisse at ex nibh. Sed sollicitudin, lorem ut congue fermentum, nisl purus congue nunc, a efficitur orci metus id orci.

Curabitur mi ligula, bibendum ac mauris et, elementum vestibulum tellus. Integer sollicitudin dui vel justo porttitor accumsan. Nulla dolor lorem, pretium lacinia nunc at, maximus fringilla nunc. Sed in ligula lectus. Nullam tincidunt mattis elit eget convallis. Cras pharetra dolor et tristique congue. Cras consequat placerat rhoncus. Morbi quis scelerisque justo, vel feugiat purus. Morbi tempor, lacus sit amet porta aliquam, augue ante faucibus enim, eget suscipit est metus non erat. Pellentesque et leo tristique, ultrices dui eu, cursus est.

Phasellus fermentum sem vitae neque rutrum feugiat. In suscipit quis ex ut porta. Curabitur nec vulputate felis. Aliquam erat volutpat. Nulla id justo sollicitudin, fermentum ligula sed, egestas sapien. Mauris ac volutpat libero. Aenean eleifend euismod urna, ac congue lectus porttitor ac. Donec a elit dui. Maecenas non pellentesque dui. Aenean eget tincidunt mauris. Phasellus interdum, leo vitae dapibus eleifend, ante ex dapibus sapien, a luctus libero nulla id ipsum. Nam ipsum purus, condimentum in aliquam et, rutrum vel dolor. Proin a justo quis nunc condimentum dictum in a magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Fusce quis commodo orci. Phasellus vel sagittis sapien. Proin vel consequat felis. Quisque quis neque nec nulla pharetra placerat. Vivamus eleifend tortor id orci finibus lobortis. Nunc lorem est, iaculis et ipsum sit amet, auctor congue risus. Aliquam at ex interdum, aliquam ante sit amet, blandit nibh. Etiam efficitur, justo nec consectetur congue, mi dui fringilla ante, et blandit dolor ante ut erat. Sed eu massa non nisl ultricies vulputate. Quisque efficitur arcu eget sem dapibus, eu semper lacus fringilla. 
""",
            "image_path": "lorem.bmp",
            "image_alt": "Picture of words Lorem ipsum"
        },
        {
            "title": "Who is the best mathematician?",
            "author": "A Based Guy",
            "content": "Paul Erdős (Hungarian: Erdős Pál [ˈɛrdøːʃ ˈpaːl]; 26 March 1913 – 20 September 1996) was a renowned Hungarian mathematician. He was one of the most prolific mathematicians and producers of mathematical conjectures[2] of the 20th century.[3] He was known both for his social practice of mathematics (he engaged more than 500 collaborators) and for his eccentric lifestyle (Time magazine called him The Oddball's Oddball).[4] He devoted his waking hours to mathematics, even into his later years—indeed, his death came only hours after he solved a geometry problem at a conference in Warsaw. Erdős pursued and proposed problems in discrete mathematics, graph theory, number theory, mathematical analysis, approximation theory, set theory, and probability theory.[5] Much of his work centered around discrete mathematics, cracking many previously unsolved problems in the field. He championed and contributed to Ramsey theory, which studies the conditions in which order necessarily appears. Overall, his work leaned towards solving previously open problems, rather than developing or exploring new areas of mathematics. ",
            "image_path": "erdos.bmp",
            "image_alt": "Image of Paul Erdos"
        },
        {
            "title": "What grade will I get?",
            "author": "God",
            "content": "God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.God says: A.",
            "image_path": "a.bmp",
            "image_alt": "Image of A+"
        },
        {
            "title": "Who is the best programmer to ever live?",
            "author": "Simponic",
            "content": "It is a tough debate. I honestly believe it could be Terry Davis. While Richard Stallman is a close second, Stallman never had to deal with the struggles of insane manic episodes like Terry did. And yet Terry accomplished as much or even more than Stallman.",
            "image_path": "terry.jpg",
            "image_alt": "Image of Terry Davis"
        },
        {
            "title": "Who is the best youtuber?",
            "author": "Simponic",
            "content": "3Blue1Brown is a math YouTube channel created by Grant Sanderson. The channel focuses on higher mathematics with a distinct visual perspective. Topics covered include linear algebra, calculus, neural networks, the Riemann hypothesis, Fourier transform,[5] quaternions and topology.[6] As of February 2021, the channel has 3.43 million subscribers. Sanderson graduated from Stanford University in 2015 with a bachelor's degree in math. He worked for Khan Academy from 2015 to 2016 as part of their content fellowship program, producing videos and articles about multivariable calculus, after which he started focusing his full attention on 3Blue1Brown. 3Blue1Brown started as a personal programming project in early 2015. In a podcast of Showmakers, Sanderson explained that he wanted to practice his coding skills and decided to make a graphics library in Python, which eventually became the open-source project Manim (short for mathematical animations).[8] To have a goal for the project, he decided to create a video with the library and uploaded it to YouTube. On March 4, 2015, he uploaded his first video. He started to publish more videos and improve the graphics tool.",
            "image_path": "grant.bmp",
            "image_alt": "Image of Grant Sanderson"
        },
        {
            "title": "A random post",
            "author": "Simponic",
            "content": "Elephants are the largest existing land animals. Three species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant. Elephantidae is the only surviving family of the order Proboscidea; extinct members include the mastodons. The family Elephantidae also contains several now-extinct groups, including the mammoths and straight-tusked elephants. African elephants have larger ears and concave backs, whereas Asian elephants have smaller ears, and convex or level backs.",
            "image_path": "elephant.jpg",
            "image_alt": "Image of an elephant"
        }
    ]

    comments = [
        {
            "commenter": "Chuck Norris",
            "email": "gmail@chucknorris.com",
            "content": "I am Chuck Norris. I am strong."
        },
        {
            "commenter": "The Big Chungus",
            "email": "bigchungo@jongulo.inc",
            "content": "I am the funniest meme of 2018."
        },
        {
            "commenter": "The Big Blungus",
            "email": "bigblungo@chungulo.inc",
            "content": "I am the epicest meme of 2020."
        },
        {
            "commenter": "My Radeon Rx 580",
            "email": "radeon@loganpc.com",
            "content": "PLEASE STOP MINING ETHEREUM ON ME PLEASEE IM BEGGING"
        },
        {
            "commenter": "God",
            "email": "god@god.god",
            "content": "I am God. I am unpolitcal and am not here to judge anyone."
        },
        {
            "commenter": "An elephant",
            "email": "Elephant@elephant.com",
            "content": "I have tusks."
        }
    ]

    Blog = apps.get_model('blog', 'Blog')
    Comment = apps.get_model('blog', 'Comment')

    blog0 = Blog(author=blogs[0]["author"], content=blogs[0]["content"], title=blogs[0]["title"], posted=randomDateTime(), image_path=blogs[0]["image_path"], image_alt=blogs[0]["image_alt"])
    blog0.save()
    blog1 = Blog(author=blogs[1]["author"], content=blogs[1]["content"], title=blogs[1]["title"], posted=randomDateTime(), image_path=blogs[1]["image_path"], image_alt=blogs[1]["image_alt"])
    blog1.save()
    blog2 = Blog(author=blogs[2]["author"], content=blogs[2]["content"], title=blogs[2]["title"], posted=randomDateTime(), image_path=blogs[2]["image_path"], image_alt=blogs[2]["image_alt"])
    blog2.save()
    blog3 = Blog(author=blogs[3]["author"], content=blogs[3]["content"], title=blogs[3]["title"], posted=randomDateTime(), image_path=blogs[3]["image_path"], image_alt=blogs[3]["image_alt"])
    blog3.save()
    blog4 = Blog(author=blogs[4]["author"], content=blogs[4]["content"], title=blogs[4]["title"], posted=randomDateTime(), image_path=blogs[4]["image_path"], image_alt=blogs[4]["image_alt"])
    blog4.save()
    blog5 = Blog(author=blogs[5]["author"], content=blogs[5]["content"], title=blogs[5]["title"], posted=randomDateTime(), image_path=blogs[5]["image_path"], image_alt=blogs[5]["image_alt"])
    blog5.save()

    for i in [blog0, blog1, blog2, blog3, blog4, blog5]:
        random.shuffle(comments)
        for j in range(random.randint(2,5)):
            i.comment_set.create(commenter=comments[j]["commenter"],email=comments[j]["email"],content=comments[j]["content"], posted=randomDateTime())

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
