# Generated by Django 3.1.7 on 2021-03-04 04:07

from django.db import migrations
from django.utils import timezone

def populate_db(apps, schema_editor):
    Choice = apps.get_model('polls', 'Choice')
    Question = apps.get_model('polls', 'Question')

    # Add new questions about Pizza
    # Remember to call the .save() method for each new object!
    pizza_q = Question(question_text="Best kind of pizza?", pub_date=timezone.now())
    pizza_q.save()

    pepperoni = Choice(question=pizza_q, choice_text="Carnivore", votes=27)
    pepperoni.save()

    hawaiian = Choice(question=pizza_q, choice_text="The Real Dill", votes=13)
    hawaiian.save()

    combination = Choice(question=pizza_q, choice_text="Marghie", votes=42)
    combination.save()

    meat_lovers = Choice(question=pizza_q, choice_text="Carmen", votes=78)
    meat_lovers.save()


    # Add new questions about James Bond
    jamesbond_q = Question(question_text="Best James Bond actor?", pub_date=timezone.now())
    jamesbond_q.save()

    sean = Choice(question=jamesbond_q, choice_text="Sean Connery", votes=92)
    sean.save()

    pierce = Choice(question=jamesbond_q, choice_text="Pierce Brosnan", votes=47)
    pierce.save()

    roger = Choice(question=jamesbond_q, choice_text="Roger Moore", votes=29)
    roger.save()

    daniel = Choice(question=jamesbond_q, choice_text="daniel craig", votes=44)
    daniel.save()



class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
